permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author:
  name: 王敏君
  email: wangminjun0704@icloud.com
  link: http://kingstal.github.io/
  weibo: http://weibo.com/minjun0704
  github: https://github.com/kingstal

# 站点信息
title: 王敏君的博客
description: 非淡泊无以明志，非宁静无以致远
url: http://kingstal.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/image/avatar.png
favicon: /assets/image/avatar.ico

# google analytics 设置
ga:
  id: UA-59508561-1
  url: kingstal.github.io/

# disqus 设置
disqus:
  shortname: wangminjun
